# Generated by Django 5.0.6 on 2024-06-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], verbose_name='Размер')),
                ('friendliness', models.IntegerField(verbose_name='Дружелюбность')),
                ('trainability', models.IntegerField(verbose_name='Тренируемость')),
                ('shedding_amount', models.IntegerField(verbose_name='Количество линек')),
                ('exercise_needs', models.IntegerField(verbose_name='Потребности в упражнениях')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('favorite_food', models.CharField(max_length=100, verbose_name='Любимая еда')),
                ('favorite_toy', models.CharField(max_length=100, verbose_name='Любимая игрушка')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('friendliness__gte', 1), ('friendliness__lte', 5)), name='friendliness_check'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('trainability__gte', 1), ('trainability__lte', 5)), name='trainability_check'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('shedding_amount__gte', 1), ('shedding_amount__lte', 5)), name='shedding_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.CheckConstraint(check=models.Q(('exercise_needs__gte', 1), ('exercise_needs__lte', 5)), name='exercise_needs_check'),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dog_app.breed', verbose_name='Порода'),
        ),
        migrations.AddConstraint(
            model_name='dog',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 0)), name='age_check'),
        ),
    ]
