"""create tables

Revision ID: 134c7cac8a6b
Revises: 
Create Date: 2024-05-31 23:01:29.463581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134c7cac8a6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_product_id', sa.String(), nullable=False),
    sa.Column('exchange_product_name', sa.String(), nullable=False),
    sa.Column('oil_id', sa.String(), nullable=False),
    sa.Column('delivery_basis_id', sa.String(), nullable=False),
    sa.Column('delivery_basis_name', sa.String(), nullable=False),
    sa.Column('delivery_type_id', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('total', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
