"""add updated_on

Revision ID: bcbd2e14f513
Revises: 90d3e1e8bf6d
Create Date: 2024-06-07 19:17:13.533110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcbd2e14f513'
down_revision: Union[str, None] = '90d3e1e8bf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spimex_trading_results', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.alter_column('spimex_trading_results', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spimex_trading_results', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('spimex_trading_results', 'updated_on')
    # ### end Alembic commands ###
