"""create tables

Revision ID: 09d3b58a8c86
Revises: 
Create Date: 2024-05-31 17:07:12.082494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d3b58a8c86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_city', sa.String(), nullable=False),
    sa.Column('days_delivery', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('step',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_step', sa.Enum('INACTIVE', 'IN_TRANSIT', 'DELIVERED', name='stage'), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_client', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('buy',
    sa.Column('buy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buy_description', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('buy_id')
    )
    op.create_table('buy_book',
    sa.Column('buy_book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('buy_book_id')
    )
    op.create_table('buy_step',
    sa.Column('buy_step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buy_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('date_step_beg', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('date_step_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.buy_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.step_id'], ),
    sa.PrimaryKeyConstraint('buy_step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy_step')
    op.drop_table('buy_book')
    op.drop_table('buy')
    op.drop_table('client')
    op.drop_table('book')
    op.drop_table('step')
    op.drop_table('genre')
    op.drop_table('city')
    op.drop_table('author')
    # ### end Alembic commands ###
